apiVersion: v1
kind: Service
metadata:
  name: axon-server
spec:
  type: ClusterIP
  ports:
    - port: 8024
      targetPort: 8024
      protocol: TCP
      name: http
    - port: 8124
      targetPort: 8124
      protocol: TCP
      name: grpc
  selector:
    app: axonserver