apiVersion: v1
kind: Service
metadata:
  name: axonserver-external
  namespace: default
spec:
  type: ExternalName
  externalName: 172.17.0.1  # For Docker Desktop
  ports:
    - port: 8124
      targetPort: 8124
      protocol: TCP