version: "3.8"
services:
  order-db:
    image: postgres
    container_name: order-pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  order-pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: order-pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  payment-db:
    image: postgres
    container_name: payment_pgdb
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_payment-pgdata:/var/lib/postgresql/data
  payment-pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - payment_pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
  local_payment-pgdata:
  payment_pgadmin-data:    