apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: { { .Release.Name } }-product-catalog-service-app
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  type: LoadBalancer