apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Release.Name } }-product-catalog-service-deployment
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Release.Name } }-product-catalog-service-app
  template:
    metadata:
      labels:
        app: { { .Release.Name } }-product-catalog-service-app
    spec:
      containers:
          - name: { { .Release.Name } }-product-catalog-service-app
            image: { { .Values.image.repository } }:{{ .Values.image.tag }}
            imagePullPolicy: { { .Values.image.pullPolicy } }
            ports:
              - containerPort: 8080
            env:
              - name: SPRING_DATASOURCE_URL
                value: { { include "spring-app.fullMongoDBConnectionURL" . | quote } }
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: MONGO_INITDB_ROOT_USERNAME
              - name: SPRING_DATASOURCE_PASSWORD
                #value: password
                valueFrom:
                  secretKeyRef:
                    name: mongodb-secret
                    key: MONGO_INITDB_ROOT_PASSWORD
              - name: KAFKA_URL
                value: kafka-service:9092
              - name: AXON_URL
                value: axon-server:8124